import {
  Article,
  ChildCare,
  ColorLens,
  ConnectWithoutContact,
  Engineering,
  Favorite,
  History,
  Language,
  MenuBook,
  Paid,
  Pets,
  Place,
  Science,
} from "@mui/icons-material";

export const subjects = [
  {
    id: 1,
    title: "Arts",
    icon: <ColorLens className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Architecture" },
      { id: 2, value: "Art Instruction" },
      { id: 3, value: "Art History" },
      { id: 4, value: "Dance" },
      { id: 5, value: "Design" },
      { id: 6, value: "Fashion" },
      { id: 7, value: "Film" },
      { id: 8, value: "Graphic Design" },
      { id: 9, value: "Music" },
      { id: 10, value: "Music Theory" },
      { id: 11, value: "Painting" },
      { id: 12, value: "Photography" },
    ],
  },
  {
    id: 2,
    title: "Animals",
    icon: <Pets className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Bears" },
      { id: 2, value: "Cats" },
      { id: 3, value: "Kittens" },
      { id: 4, value: "Dogs" },
      { id: 5, value: "Puppies" },
    ],
  },
  {
    id: 3,
    title: "Fiction",
    icon: <Engineering className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Fantasy" },
      { id: 2, value: "Historical Fiction" },
      { id: 3, value: "Horror" },
      { id: 4, value: "Humor" },
      { id: 5, value: "Literature" },
      { id: 6, value: "Magic" },
      { id: 7, value: "Mystery and detective stories" },
      { id: 8, value: "Plays" },
      { id: 9, value: "Poetry" },
      { id: 10, value: "Romance" },
      { id: 11, value: "Science Fiction" },
      { id: 12, value: "Thriller" },
      { id: 13, value: "Young Adult" },
    ],
  },
  {
    id: 4,
    title: "Science & Mathematics",
    icon: <Science className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Biology" },
      { id: 2, value: "Chemistry" },
      { id: 3, value: "Mathematics" },
      { id: 4, value: "Physics" },
      { id: 5, value: "Programming" },
    ],
  },
  {
    id: 5,
    title: "Business & Finance",
    icon: <Paid className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Management" },
      { id: 2, value: "Entrepreneurship" },
      { id: 3, value: "Business Economics" },
      { id: 4, value: "Business Success" },
      { id: 5, value: "Finance" },
    ],
  },
  {
    id: 6,
    title: "Children's",
    icon: <ChildCare className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Kids Books" },
      { id: 2, value: "Stories in Rhyme" },
      { id: 3, value: "Baby Books" },
      { id: 4, value: "Bedtime Books" },
      { id: 5, value: "Picture Books" },
    ],
  },
  {
    id: 7,
    title: "History",
    icon: <History className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Ancient Civilization" },
      { id: 2, value: "Archaeology" },
      { id: 3, value: "Anthropology" },
      { id: 4, value: "World War II" },
      { id: 5, value: "Social Life and Customs" },
    ],
  },
  {
    id: 8,
    title: "Health & Wellness",
    icon: <Favorite className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Cooking" },
      { id: 2, value: "Cookbooks" },
      { id: 3, value: "Mental Health" },
      { id: 4, value: "Exercise" },
      { id: 5, value: "Nutrition" },
      { id: 6, value: "Self-help" },
    ],
  },
  {
    id: 9,
    title: "Biography",
    icon: <Article className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Autobiographies" },
      { id: 2, value: "History" },
      { id: 3, value: "Politics and Government" },
      { id: 4, value: "World War II" },
      { id: 5, value: "Women" },
      { id: 6, value: "Kings and Rulers" },
      { id: 7, value: "Composers" },
      { id: 8, value: "Artists" },
    ],
  },
  {
    id: 10,
    title: "Social Sciences",
    icon: <ConnectWithoutContact className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Anthropology" },
      { id: 2, value: "Religion" },
      { id: 3, value: "Political Science" },
      { id: 4, value: "Psychology" },
    ],
  },
  {
    id: 11,
    title: "Places",
    icon: <Place className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "Brazil" },
      { id: 2, value: "India" },
      { id: 3, value: "Indonesia" },
      { id: 4, value: "United States" },
    ],
  },
  {
    id: 12,
    title: "Textbooks",
    icon: <MenuBook className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "History" },
      { id: 2, value: "Mathematics" },
      { id: 3, value: "Geography" },
      { id: 4, value: "Psychology" },
      { id: 5, value: "Algebra" },
      { id: 6, value: "Education" },
      { id: 7, value: "Business & Economics" },
      { id: 8, value: "Science" },
      { id: 9, value: "Chemistry" },
      { id: 10, value: "English Language" },
      { id: 11, value: "Physics" },
      { id: 12, value: "Computer Science" },
    ],
  },
  {
    id: 13,
    title: "Books by Language",
    icon: <Language className="text-black scale-125 mr-2" />,
    subjects: [
      { id: 1, value: "English" },
      { id: 2, value: "French" },
      { id: 3, value: "Spanish" },
      { id: 4, value: "German" },
      { id: 5, value: "Russian" },
      { id: 6, value: "Italian" },
      { id: 7, value: "Chinese" },
      { id: 8, value: "Japanese" },
    ],
  },
];
